Automated searches, batch counts, spark specific agent configs, etc.

diff --git a/elasticsearch/bin/rapi b/elasticsearch/bin/rapi
--- a/elasticsearch/bin/rapi
+++ b/elasticsearch/bin/rapi
@@ -23,29 +23,29 @@ body=$3
 
 if [ "$method" == "" ] || [ "$url_path" == "" ]
 then 
-  echo "both the method and url_path path must be supplied"  >&2 
-  echo "Method=$method" >&2 
-  echo "URL Path=$url_path" >&2 
+  echo `date -u +%Y-%m-%dT%H:%M:%S.%N` " | both the method and url_path path must be supplied"  >&2 
+  echo `date -u +%Y-%m-%dT%H:%M:%S.%N` " | Method=$method" >&2 
+  echo `date -u +%Y-%m-%dT%H:%M:%S.%N` " | URL Path=$url_path" >&2 
   exit 1
 fi
 
 
 if [[ "${url_path:0:1}" != "/" ]]; 
 then
-  echo "The URL path '$url_path' must begin with a '/'"  >&2 
+  echo `date -u +%Y-%m-%dT%H:%M:%S.%N` " | The URL path '$url_path' must begin with a '/'"  >&2 
   exit 1
 fi
 
-if ! ( [ "$method" == "PUT" ] || [ "$method" == "GET" ] || [ "$method" == "POST" ] )
+if ! ( [ "$method" == "PUT" ] || [ "$method" == "GET" ] || [ "$method" == "POST" ] || [ "$method" == "DELETE" ] )
 then
-  echo "Method must be one of PUT, GET, or POST and not $method"  >&2 
+  echo `date -u +%Y-%m-%dT%H:%M:%S.%N` "Method must be one of PUT, GET, or POST and not $method"  >&2 
   exit 1
 fi
 
 if [ "$method" == "PUT" ]
 then
   if ! [ -f $body ] ;  then 
-    echo "PUT body must be a file that exists. \"$body\" does not exist" >&2 
+    echo `date -u +%Y-%m-%dT%H:%M:%S.%N` " | PUT body must be a file that exists. \"$body\" does not exist" >&2 
     exit 1
   else
     body_line="--data-binary @$body"
@@ -56,7 +56,7 @@ else
     body_line=""
   else 
     if ! [ -f $body ] ;  then 
-      echo "GET or POST body must be a file that exists. \"$body\" does not exist"  >&2 
+      echo `date -u +%Y-%m-%dT%H:%M:%S.%N` " | GET or POST body must be a file that exists. \"$body\" does not exist"  >&2 
       exit 1 
     else
       body_line="--data-binary @$body"
@@ -73,12 +73,12 @@ fi
 
 
 
-echo "Executing $method on $url_path with body '$body'" >&2 
+echo `date -u +%Y-%m-%dT%H:%M:%S.%N` " | Executing $method on $url_path with body '$body'" >&2 
 
 if [ "$body_line" == "" ]
 then
   # docker compose exec -it init-index curl 
-  result=$($command \
+  result=$($command --write-out "%{http_code}"\
             --no-progress-meter \
             --request $method "https://es01:9200$url_path" \
             --cacert config/certs/ca/ca.crt \
@@ -97,20 +97,11 @@ else
   status=$?
 fi
 
-#echo -e "Status is $status\nResult is: $result"
-
 if [ $status -ne 0 ]; then
-    echo "Error: curl failed with code $?" >&2
+    echo `date -u +%Y-%m-%dT%H:%M:%S.%N` " | Error: curl failed with code $status" >&2
     exit $status
 else 
-  # see if HTTP request errored
-  hstatus=$(echo $result | jq -r .status)
-  if [ "$hstatus" == "200" ] || [ "$hstatus" == "null" ]; then
-    status=0
-  else 
-    echo "HTTP error: $hstatus" >&2
-    status=1
-  fi
+    echo `date -u +%Y-%m-%dT%H:%M:%S.%N` " | curl completed successfully" >&2
 fi
 echo $result
 exit $status
